apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: ns-fastapi-2024mt03072
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: img-2024mt03072:v7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: config-2024mt03072
