apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ns-fastapi-2024mt03072
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'fastapi'
        metrics_path: /metrics
        static_configs:
        - targets: ['fastapi-service:8000']

      - job_name: 'cadvisor'
        metrics_path: /metrics/cadvisor
        static_configs:
        - targets: ['192.168.49.2:10255']
      