apiVersion: v1
kind: Pod
metadata:
    name: example-pod
    namespace: ns-fastapi-2024mt03072
spec:
    initContainers:
    -   name: init-container
        image: busybox
        command: ["sh", "-c", "echo 'Initializing...'; sleep 5; echo 'Init Complete'"]
    containers:
    -   name: primary-container
        image: nginx
        ports:
        -   containerPort: 80
    -   name: sidecar-container
        image: busybox
        command: ["sh", "-c", "while true; do echo 'Sidecar running...'; sleep 10; done"]